version: '2'

services:
### daily-report-service ####
    daily-report-service:
        image: registry.thinknet.co.th/sredev/node:8
        command: yarn dev
        environment:
            NODE_PORT: '4000'
            MONGO_CONNECTION: mongodb://borbork:borbork@bar-bork-thinknet-shard-00-00-797rd.mongodb.net:27017,bar-bork-thinknet-shard-00-01-797rd.mongodb.net:27017,bar-bork-thinknet-shard-00-02-797rd.mongodb.net:27017/daily-report?ssl=true&replicaSet=bar-bork-thinknet-shard-0&authSource=admin
        ports:
            - "4000:4000"
        volumes:
            - .:/usr/src/app

### Connect Network #####
networks:
  default:
      external:
          name: daily-report-service-team